# Site settings
title:       My Grow Journal
email:
author:
description: "My humble grow journal"
baseurl:     "Base URL is the name of your repository"
url:         "URL is the git url eg https://7lpdwcaw.github.io"
date_format: "%b %-d, %Y"

# Optional features
animated: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  style: compressed
gems:
  - jekyll-paginate
  - jekyll-sitemap

# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
include: ['_pages']

# This is for plugin to generate pages automatically for data/plants.json
# uncomment this to auto-generate plant pages during jekyll server
# page_gen:
#   - data: 'plants'
#     template: 'plant'
#     name: 'name'
#     dir: 'plants'
